# Generated by Django 4.2.2 on 2023-06-07 21:11

from django.db import migrations


# Todo: this needs to be deleted shortly
def create_test_teacher(apps, schema_editor):
    Teacher = apps.get_model('api', 'Teacher')
    Teacher(name="Test Teacher").save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teachers'),
    ]

    operations = [
        migrations.RunPython(create_test_teacher)
    ]
