# Generated by Django 4.2.2 on 2023-06-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser'),
    ]

    operations = [

    ]
