# Generated by Django 4.2.2 on 2023-06-18 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_new_teacher_attrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='addedDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Added Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='ratingCommunication',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='ratingMaterial',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='ratingOrganized',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
