# Generated by Django 4.2.2 on 2023-06-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_teacher_addeddate_teacher_ratingcommunication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('initials', models.CharField(max_length=240, verbose_name='Name')),
            ],
        ),
    ]
