# Generated by Django 4.2.2 on 2023-06-19 21:43

from django.db import migrations


def create_test_teachers(apps, schema_editor):
    Teacher = apps.get_model('api', 'Teacher')
    Teacher(name="Pablo Kipreos", ratingOrganized=5, ratingCommunication=5, ratingMaterial=5).save()
    Teacher(name="Klapp", ratingOrganized=3, ratingCommunication=1, ratingMaterial=1).save()
    Teacher(name="Felipe Galan", ratingOrganized=4, ratingCommunication=3, ratingMaterial=4).save()


def create_test_courses(apps, schema_editor):
    Course = apps.get_model('api', 'Course')
    Course(name="Estructuras de Datos y Algoritmos", description="Curso de Algoritmos y Estructuras de Datos", initials="IIC2133").save()
    Course(name="Programacion Avanzada", description="Curso de Programacion Avanzada", initials="IIC2143").save()
    Course(name="Taller de Ingenieria de Software", description="Curso de Taller de Ingenieria de Software", initials="IIC2153").save()
    Course(name="Taller de Programacion", description="Curso de Taller de Programacion", initials="IIC2113").save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_course'),
    ]

    operations = [
        migrations.RunPython(create_test_teachers),
        migrations.RunPython(create_test_courses),
    ]
