# Generated by Django 4.2.2 on 2023-06-21 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_course_teachers_teacher_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingOrganization', models.FloatField()),
                ('ratingClass', models.FloatField()),
                ('ratingMaterial', models.FloatField()),
                ('comment', models.TextField(verbose_name='Comment')),
                ('addedDate', models.DateField(auto_now_add=True, verbose_name='Added Date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customuser')),
            ],
        ),
    ]
