# Generated by Django 4.2.2 on 2023-07-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_review_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0),
        ),
    ]
