# Generated by Django 4.2.2 on 2023-07-10 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_review_ratingclass_alter_review_ratingmaterial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
    ]
