name: Push to AWS (EC2)

on:
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]

jobs:
  deploy:
    name: Deploy main branch to EC2 instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Clone files to server and initiate docker container
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd ~/${{ secrets.TARGET_DIR }}
            echo ls