name: Push to AWS (EC2)

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy main branch to EC2 instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Clone files to server and initiate docker container
        uses: appleboy/ssh-action@v0.1.10
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd ~/${{ secrets.TARGET_DIR }}
            echo ls