name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
      - 'eslintrc.js'
  push:
jobs:
  Test:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v2

      - name: Run Docker Compose and tests
        run: docker compose -f docker-compose.yml up -d --build
      
      - name: Wait for the service to be ready
        run: docker ps